### ISSUE TITLE
После загрузки фотографии трассы она отображается не на весь экран

### ISSUE THREAD

**Issue by levenkov** [bitia-ru/gekkon-m-frontend#154]
И иногда перевернута.

**Comment by SvetlanaBatova** [comment]
![image](https://user-images.githubusercontent.com/34437046/98533336-e310d480-2293-11eb-8661-3977881df407.png)
Если смотреть более ранние ветки, то было так, т.е. вверху была темная полоса, на которой отображаются кнопки, а изображение на нее не находило, сейчас эта полоса прозрачная и видно окно под ней. Что должно быть?

Вариант, когда фото перевернуто у меня не воспроизводится

**Comment by SvetlanaBatova** [comment]
![image](https://user-images.githubusercontent.com/34437046/98534175-1d2ea600-2295-11eb-90f6-857acbea32ad.png)
Если растягивать фото на весь экран, то надо делать как-то так, не уверена, что это удобно

**Comment by levenkov** [comment]
Второй вариант однозначно неверный, т.к. можно растянуть зону кропа и потом не получится добраться до верхних углов. Надо возвращать первый вариант.
