### ISSUE TITLE
Селектор цвета зацепа/маркировки: добавить возможность сброса

### ISSUE THREAD

**Issue by levenkov** [bitia-ru/gekkon-m-frontend#157]
Продуктовый тикет: https://github.com/bitia-ru/gekkon/issues/10

**Comment by SergBlack** [comment]
Такая фича уже есть в приложении. Или имелся ввиду какой-то баг?

**Comment by levenkov** [comment]
Тикет заведен по ошибке, функциональность уже есть в мастере.
